### ISSUE TITLE
Can't load list of games

### ISSUE THREAD

**Issue by WillieWookiee** [micahg/plugin.video.mlslive#6]
This might already be known, and maybe it has to do with the switch to ESPN+, but I already have an account on MLS Live and can sign in through the website, but the addon is giving me this traceback now. 

Is this a known issue with the switchover?

03:30:35.230 T:544883159264   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 21: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mlslive/default.py", line 269, in <module>
                                                createGamesMenu(complete=True, offset=dt)
                                              File "/storage/.kodi/addons/plugin.video.mlslive/default.py", line 80, in createGamesMenu
                                                title = mls.getGameString(game, __language__(30008))
                                              File "/storage/.kodi/addons/plugin.video.mlslive/mlslive.py", line 401, in getGameString
                                                dt_str)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 21: ordinal not in range(128)
                                            -->End of Python script error report<--

**Comment by micahg** [comment]
Yeah, looks like they've switched over.
